spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.9.188.179:3306/scuec?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true

    username: scuec
    password: scuecljs
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
